from time import sleep

from detect_and_shoot import turn_on_pump, turn_off_pump, turn_on_lights, turn_off_lights, go_to_sleep


print("Testing detect and shoot trap")
sleep(1)
print("shooting in 3")
sleep(1)
print("shooting in 2")
sleep(1)
print("shooting in 1")
sleep(1)
turn_on_pump()
sleep(1)
turn_off_pump()
sleep(1)
print("Testing light")
sleep(1)
turn_on_lights()
sleep(1)
turn_off_lights()
sleep(1)
turn_on_lights()
sleep(1)
turn_off_lights()
sleep(1)
turn_on_lights()
sleep(1)
turn_off_lights()
sleep(1)
print("going to sleep in 3")
sleep(1)
print("going to sleep in 2")
sleep(1)
print("going to sleep in 1")
sleep(1)
go_to_sleep()